steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/adminer:latest', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/adminer']
    #waitFor: ['tag-adminer']
    id: 'push-adminer'
  
  - name: 'gcr.io/cloud-builders/gcloud'
    args: 
      - 'run'
      - 'deploy'
      - 'adminer'
      - '--image=gcr.io/$PROJECT_ID/adminer'
      - '--region=europe-west1'
      - '--network=grc.io/fluted-oath-420013/global/networks/peering-network'
      - '--platform=managed'
