steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/wordpress:latest', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/wordpress']
    #waitFor: ['tag-adminer']
    id: 'push-adminer'
  
  - name: 'gcr.io/cloud-builders/gcloud'
    args: 
      - 'run'
      - 'deploy'
      - 'wordpress'
      - '--image=gcr.io/$PROJECT_ID/wordpress'
      - '--region=europe-west1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--vpc-connector=$_VPC_CONNECTOR'
      - '--port=80'
