#steps:
#  - name: 'gcr.io/cloud-builders/docker'
#    args: ['build', '-t', 'gcr.io/$PROJECT_ID/wordpress:latest', '.']
#    env:
#      - 'WORDPRESS_DB_HOST=10.100.0.3'
#      - 'WORDPRESS_DB_USER=user'
#      - 'WORDPRESS_DB_PASSWORD=password'
#      - 'WORDPRESS_DB_NAME=my-database'
#
#  - name: 'gcr.io/cloud-builders/docker'
#    args: ['push', 'gcr.io/$PROJECT_ID/wordpress']
#    id: 'push-wordpress'
#    #waitFor: ['tag-adminer']
#  
#  - name: 'gcr.io/cloud-builders/gcloud'
#    args: 
#      - 'run'
#      - 'deploy'
#      - 'wordpress'
#      - '--image=gcr.io/$PROJECT_ID/wordpress'
#      - '--region=europe-west1'
#      - '--platform=managed'
#      - '--add-cloudsql-instances=fluted-oath-420013:europe-west1:my-database'
#      - '--allow-unauthenticated'
#      - '--vpc-connector=$_VPC_CONNECTOR'
#      - '--port=80'
#    env:
#      - 'WORDPRESS_DB_HOST=10.100.0.3'
#      - 'WORDPRESS_DB_USER=user'
#      - 'WORDPRESS_DB_PASSWORD=password'
#      - 'WORDPRESS_DB_NAME=my-database'
#
#options:
#  env:
#    - 'PROJECT_ID=$PROJECT_ID'
#    - 'VPC_CONNECTOR=$_VPC_CONNECTOR'

steps:
  #- name: 'gcr.io/cloud-builders/docker'
  #  args: ['build', '-t', 'gcr.io/$PROJECT_ID/wordpress:latest', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--build-arg', 'WORDPRESS_DB_HOST=10.7.0.3', '--build-arg', 'WORDPRESS_DB_USER=user', '--build-arg', 'WORDPRESS_DB_PASSWORD=password', '--build-arg', 'WORDPRESS_DB_NAME=my-database', '-t', 'gcr.io/$PROJECT_ID/wordpress:latest', '.']


  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/wordpress']
    #waitFor: ['tag-adminer']
    id: 'push-wordpress'
  
  - name: 'gcr.io/cloud-builders/gcloud'
    args: 
      - 'run'
      - 'deploy'
      - 'wordpress'
      - '--image=gcr.io/$PROJECT_ID/wordpress'
      - '--region=europe-west1'
      - '--platform=managed'
      - '--add-cloudsql-instances'
      - 'fluted-oath-420013:europe-west1:my-database'
      - '--allow-unauthenticated'
      - '--vpc-connector=projects/fluted-oath-420013/locations/europe-west1/connectors/peering-tool'
      - '--port=80'
      - '--set-env-vars=WORDPRESS_DB_HOST=10.7.0.3,WORDPRESS_DB_USER=user,WORDPRESS_DB_PASSWORD=password,WORDPRESS_DB_NAME=my-database'