
version: '3.7'
services:
  wordpress:
    build:
      context: . 
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_USER: alepinto
      WORDPRESS_DB_PASSWORD: pass
      WORDPRESS_DB_NAME: wordpress-db
      WORDPRESS_DB_HOST: mysql
    depends_on:
      - mysql
    networks:
      - wordpress-net
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wordpress-db
      MYSQL_USER: alepinto
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - wordpress-net
networks:
  wordpress-net:
volumes:
  mysql_data:

#version: '3.8'
#
#services:
#  db:
#    image: mysql:5.7
#    volumes:
#      - db_data:/var/lib/mysql
#    restart: always
#    environment:
#      MYSQL_ROOT_PASSWORD: rootpassword
#      MYSQL_DATABASE: my-database
#      MYSQL_USER: user
#      MYSQL_PASSWORD: password
#    networks:
#      - wp-net
#
#  wordpress:
#    depends_on:
#      - db
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - "8080:80"
#    restart: always
#    environment:
#      WORDPRESS_DB_HOST: db:3306
#      WORDPRESS_DB_USER: user
#      WORDPRESS_DB_PASSWORD: password
#      WORDPRESS_DB_NAME: my-database
#    networks:
#      - wp-net
#    volumes:
#      - wordpress_data:/var/www/html
#
#networks:
#  wp-net:
#    driver: bridge
#
#volumes:
#  db_data:
#  wordpress_data:
#