version: '3.8'

services:
  mongodb:
    build:
      context: .
      dockerfile: Dockerfile-mongo  # Nombre del nuevo Dockerfile para MongoDB
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  my-go-app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mongodb

  mongodb-client:
    image: mongo
    command: ["mongo"]
    depends_on:
      - mongodb

volumes:
  mongodb_data:

